apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: student-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/named-inn-450611-t5/k8s-demo-app/student-service
          ports:
            - name: http1
              containerPort: 80