server:
  servlet:
    context-path: /student-service


#spring.application.name=student-service
#spring.application.name=student-service
#spring.datasource.url=jdbc:postgresql://localhost:5432/Demo

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///postgres
    username: javadeveloper
    password: java
    hikari:
#      minimum-idle: 2
#      maximum-pool-size: 5
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: named-inn-450611-t5:us-central1:student
#        enableIamAuth: true
#        sslmode: disable

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect : org.hibernate.dialect.PostgreSQL10Dialect


#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql:///${DB_DATABASE:postgres}
#    username: ${DB_USERNAME:student-cloudrun@noted-ensign-357703.iam}
#    password: ${DB_PASSWORD:3213}
#    hikari:
#      minimum-idle: 2
#      maximum-pool-size: 5
#      data-source-properties:
#        socketFactory: com.google.cloud.sql.postgres.SocketFactory
#        cloudSqlInstance: named-inn-450611-t5:us-central1:student
#        enableIamAuth: true
#        sslmode: disable
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      properties:
#        hibernate.dialect : org.hibernate.dialect.PostgreSQL10Dialect
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect